backend:
  name: git-gateway
  branch: content-updates
  commit_messages:
    create: created {{collection}} entry “{{slug}}”
    update: updated {{collection}} entry “{{slug}}”
    delete: deleted {{collection}} entry “{{slug}}”
    uploadMedia: uploaded “{{path}}”
    deleteMedia: deleted “{{path}}”
    openAuthoring: '{{message}}'

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}"
    fields:
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Heading", name: "heading", widget: "string"}
      - label: "Image Large"
        name: "image_desktop"
        widget: "image"
        hint: "File name format: fYYYY-MM-DD-desktop.jpg"
      - label: "Image Large WebP"
        name: "image_desktop_webp"
        widget: "image"
        hint: "File name format: YYYY-MM-DD-desktop.webp"
      - label: "Image 768x768"
        name: "image_large"
        widget: "image"
        hint: "File name format: YYYY-MM-DD-large.jpg"
      - label: "Image 768x768 WebP"
        name: "image_large_webp"
        widget: "image"
        hint: "File name format: YYYY-MM-DD-large.webp"
      - label: "Image 428x428"
        name: "image_mobile"
        widget: "image"
        hint: "File name format: YYYY-MM-DD-mobile.jpg"
      - label: "Image 428x428 WebP"
        name: "image_mobile_webp"
        widget: "image"
        hint: "File name format: YYYY-MM-DD-mobile.webp"
      - {label: "Content", name: "body", widget: "markdown"}
  - name: "stories"
    label: "stories"
    folder: "content/stories"
    extension: json
    create: true
    slug: "{{heading}}"
    fields:
      - {label: "First Name", name: "first_name", widget: "string"}
      - {label: "Heading", name: "heading", widget: "string"}
      - {label: "Intro", name: "intro", widget: "text"}
      - {label: "Quote", name: "quote", widget: "text"}
      - {label: "Paragraphs", name: "paragraphs", widget: "text"}
      - {label: "Image 768x768", name: "image_large", widget: "image"}
      - {label: "Image 768x768 WebP", name: "image_large_webp", widget: "image", required: false}
      - {label: "Image 428x428", name: "image_mobile", widget: "image"}
      - {label: "Image 428x428 WebP", name: "image_mobile_webp", widget: "image", required: false}
      - {label: "PayPal Link", name: "paypal_link", widget: "string", required: false}
      - {label: "Go Fund Me Link", name: "gofundme_link", widget: "string", required: false}
  - name: "team"
    label: "team"
    folder: "content/team"
    extension: json
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string", hint: "Format as: firstName-lastName"}
      - {label: "First Name", name: "first_name", widget: "string"}
      - {label: "Last Name", name: "last_name", widget: "string"}
      - label: "Roles"
        name: "roles"
        widget: "select"
        multiple: true
        options: ["design", "lead", "development", "art", "project/product", "marketing", "QA", "mentor", "founder", "co-founder"]
      - {label: "Image 748x748", name: "image_large", widget: "image", hint: "File name format: firstName-lastName-large.jpg"}
      - {label: "Image 748x748 WebP", name: "image_large_webp", widget: "image", required: false, hint: "File name format: firstName-lastName-large.webp"}
      - {label: "Image 428x428", name: "image_mobile", widget: "image", hint: "File name format: firstName-lastName-mobile.jpg"}
      - {label: "Image 428x428 WebP", name: "image_mobile_webp", widget: "image", required: false, hint: "File name format: firstName-lastName-mobile.webp"}
      - {label: "LinkedIn Link", name: "linkedin_link", widget: "string", required: false}
